name: FTP Deployment

on:
  push:
    branches:
      - main  # Trigger the deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Deploy files to FTP server
    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.1.0
      with:
        ftp-server: ftp://ftpupload.net:21    # Explicitly set FTP server with port 21
        ftp-username: icei_38523038
        ftp-password: PAiKLe7DSH2l
        local-dir: ./Rank-Maths    # Local directory to upload (change to your folder)
        server-dir: /htdocs        # Remote directory to upload files (replace in /htdocs)
